# Generated by Django 5.2.7 on 2025-10-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms_api', '0008_hacer_usuario_subida_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='faenas',
            name='ciudad',
            field=models.CharField(blank=True, db_column='Ciudad', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faenas',
            name='contacto',
            field=models.CharField(blank=True, db_column='Contacto', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='faenas',
            name='descripcion',
            field=models.TextField(blank=True, db_column='Descripcion', null=True),
        ),
        migrations.AddField(
            model_name='faenas',
            name='direccion',
            field=models.CharField(blank=True, db_column='Direccion', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faenas',
            name='email',
            field=models.EmailField(blank=True, db_column='Email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faenas',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True),
        ),
        migrations.AddField(
            model_name='faenas',
            name='region',
            field=models.CharField(blank=True, db_column='Region', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faenas',
            name='telefono',
            field=models.CharField(blank=True, db_column='Telefono', max_length=20, null=True),
        ),
    ]
