# Generated by Django 4.2.23 on 2025-11-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms_api', '0009_faenas_ciudad_faenas_contacto_faenas_descripcion_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipos',
            index=models.Index(fields=['activo'], name='idx_equipos_activo'),
        ),
        migrations.AddIndex(
            model_name='equipos',
            index=models.Index(fields=['idestadoactual'], name='idx_equipos_estado'),
        ),
        migrations.AddIndex(
            model_name='ordenestrabajo',
            index=models.Index(fields=['fechareportefalla'], name='idx_ot_fecha_reporte'),
        ),
        migrations.AddIndex(
            model_name='ordenestrabajo',
            index=models.Index(fields=['fechacreacionot'], name='idx_ot_fecha_creacion'),
        ),
        migrations.AddIndex(
            model_name='ordenestrabajo',
            index=models.Index(fields=['idestadoot', 'fechacreacionot'], name='idx_ot_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='ordenestrabajo',
            index=models.Index(fields=['idequipo', 'idestadoot'], name='idx_ot_equipo_estado'),
        ),
        migrations.AddIndex(
            model_name='ordenestrabajo',
            index=models.Index(fields=['prioridad', 'fechacreacionot'], name='idx_ot_prioridad_fecha'),
        ),
    ]
