# Generated by Django 4.2.23 on 2025-11-12 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmms_api', '0010_add_indexes_and_model_optimizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('idespecialidad', models.AutoField(db_column='IDEspecialidad', primary_key=True, serialize=False)),
                ('nombreespecialidad', models.CharField(db_column='NombreEspecialidad', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('activa', models.BooleanField(db_column='Activa', default=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidades',
                'ordering': ['nombreespecialidad'],
            },
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('idtecnico', models.AutoField(db_column='IDTecnico', primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, db_column='Cargo', max_length=100, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('no_disponible', 'No Disponible')], db_column='Estado', default='disponible', max_length=20)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('fecha_ingreso', models.DateField(blank=True, db_column='FechaIngreso', null=True)),
                ('especialidades', models.ManyToManyField(blank=True, db_column='Especialidades', related_name='tecnicos', to='cmms_api.especialidades')),
                ('usuario', models.OneToOneField(db_column='IDUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'db_table': 'tecnicos',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
    ]
