# Generated by Django 4.2.23 on 2025-11-12 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmms_api', '0011_especialidades_tecnicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasInventario',
            fields=[
                ('idcategoria', models.AutoField(db_column='IDCategoria', primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(db_column='NombreCategoria', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('activa', models.BooleanField(db_column='Activa', default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Inventario',
                'verbose_name_plural': 'Categorías de Inventario',
                'db_table': 'categoriasinventario',
                'ordering': ['nombrecategoria'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idinventario', models.AutoField(db_column='IDInventario', primary_key=True, serialize=False)),
                ('codigointerno', models.CharField(db_column='CodigoInterno', max_length=50, unique=True)),
                ('codigobarras', models.CharField(blank=True, db_column='CodigoBarras', max_length=100, null=True)),
                ('nombreitem', models.CharField(db_column='NombreItem', max_length=200)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('cantidad', models.DecimalField(db_column='Cantidad', decimal_places=2, default=0, max_digits=10)),
                ('stockminimo', models.DecimalField(db_column='StockMinimo', decimal_places=2, default=0, max_digits=10)),
                ('stockmaximo', models.DecimalField(blank=True, db_column='StockMaximo', decimal_places=2, max_digits=10, null=True)),
                ('unidadmedida', models.CharField(choices=[('unidad', 'Unidad'), ('metro', 'Metro'), ('litro', 'Litro'), ('kilogramo', 'Kilogramo'), ('caja', 'Caja'), ('rollo', 'Rollo'), ('galón', 'Galón'), ('par', 'Par'), ('juego', 'Juego')], db_column='UnidadMedida', default='unidad', max_length=20)),
                ('ubicacion', models.CharField(blank=True, db_column='Ubicacion', max_length=100, null=True)),
                ('costounitario', models.DecimalField(db_column='CostoUnitario', decimal_places=2, default=0, max_digits=12)),
                ('precioventa', models.DecimalField(blank=True, db_column='PrecioVenta', decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('descontinuado', 'Descontinuado')], db_column='Estado', default='activo', max_length=20)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('fechaactualizacion', models.DateTimeField(auto_now=True, db_column='FechaActualizacion')),
                ('idcategoria', models.ForeignKey(db_column='IDCategoria', on_delete=django.db.models.deletion.PROTECT, to='cmms_api.categoriasinventario')),
            ],
            options={
                'verbose_name': 'Item de Inventario',
                'verbose_name_plural': 'Items de Inventario',
                'db_table': 'inventario',
                'ordering': ['codigointerno'],
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedor', models.AutoField(db_column='IDProveedor', primary_key=True, serialize=False)),
                ('nombreproveedor', models.CharField(db_column='NombreProveedor', max_length=150)),
                ('rut', models.CharField(blank=True, db_column='RUT', max_length=12, null=True, unique=True)),
                ('contacto', models.CharField(blank=True, db_column='Contacto', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, db_column='Direccion', null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['nombreproveedor'],
            },
        ),
        migrations.CreateModel(
            name='MovimientosInventario',
            fields=[
                ('idmovimiento', models.AutoField(db_column='IDMovimiento', primary_key=True, serialize=False)),
                ('tipomovimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste_positivo', 'Ajuste Positivo'), ('ajuste_negativo', 'Ajuste Negativo'), ('transferencia', 'Transferencia')], db_column='TipoMovimiento', max_length=20)),
                ('cantidad', models.DecimalField(db_column='Cantidad', decimal_places=2, max_digits=10)),
                ('cantidadanterior', models.DecimalField(db_column='CantidadAnterior', decimal_places=2, max_digits=10)),
                ('cantidadnueva', models.DecimalField(db_column='CantidadNueva', decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(blank=True, db_column='Motivo', max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
                ('documento', models.CharField(blank=True, db_column='Documento', max_length=100, null=True)),
                ('fechamovimiento', models.DateTimeField(auto_now_add=True, db_column='FechaMovimiento')),
                ('idinventario', models.ForeignKey(db_column='IDInventario', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cmms_api.inventario')),
                ('idordentrabajo', models.ForeignKey(blank=True, db_column='IDOrdenTrabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.ordenestrabajo')),
                ('idproveedor', models.ForeignKey(blank=True, db_column='IDProveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.proveedores')),
                ('usuariomovimiento', models.ForeignKey(db_column='UsuarioMovimiento', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimientosinventario',
                'ordering': ['-fechamovimiento'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='idproveedor',
            field=models.ForeignKey(blank=True, db_column='IDProveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmms_api.proveedores'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='usuariocreacion',
            field=models.ForeignKey(db_column='UsuarioCreacion', on_delete=django.db.models.deletion.PROTECT, related_name='inventario_creado', to=settings.AUTH_USER_MODEL),
        ),
    ]
